# 1st task, dataset exploration and binary calssification

In [46]:
from datasets import load_dataset
dataset = load_dataset("copenlu/answerable_tydiqa")
train_set = dataset["train"]
validation_set = dataset["validation"]

Using custom data configuration copenlu--nlp_course_tydiqa-cceecfb5416d988a
Reusing dataset parquet (C:\Users\fiori\.cache\huggingface\datasets\copenlu___parquet\copenlu--nlp_course_tydiqa-cceecfb5416d988a\0.0.0\2a3b91fbd88a2c90d1dbbb32b460cf621d31bd5b05b934492fdef7d8d6f236ec)
100%|████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 14.09it/s]


In [47]:
import numpy as np
import pandas as pd
df = pd.DataFrame(train_set)
vs = pd.DataFrame(validation_set)

In [48]:
df

question_text      document_title  \
0                   Milloin Charles Fort syntyi?        Charles Fort   
1                    “ダン” ダニエル・ジャドソン・キャラハンの出身はどこ        ダニエル・J・キャラハン   
2         వేప చెట్టు యొక్క శాస్త్రీయ నామం ఏమిటి?                 వేప   
3             চেঙ্গিস খান কোন বংশের রাজা ছিলেন ?         চেঙ্গিজ খান   
4               రెయ్యలగడ్ద గ్రామ విస్తీర్ణత ఎంత?          రెయ్యలగడ్ద   
...                                          ...                 ...   
116062  Kapan Kaisar Tang Gaozu mulai menjabat ?   Kaisar Tang Gaozu   
116063                        من ابتكر المثلجات؟              مثلجات   
116064      বাংলা ব্যাকরণ মতে বিশেষণ কয় প্রকার ?              বিশেষণ   
116065                              ブラームスの出身はどこ？          ヨハネス・ブラームス   
116066     What is the population of Mahwah, NJ?  Mahwah, New Jersey   

          language                                        annotations  \
0          finnish  {'answer_start': [18], 'answer_text': ['6. elo...   
1         japanese  {'answer_start': [35], 'answer_text': ['カリフォルニ...   
2           telugu  {'answer_start': [12], 'answer_text': ['Azadir...   
3          bengali  {'answer_start': [414], 'answer_text': ['বোরজি...   
4           telugu  {'answer_start': [259], 'answer_text': ['27 హె...   
...            ...                                                ...   
116062  indonesian        {'answer_start': [-1], 'answer_text': ['']}   
116063      arabic        {'answer_start': [-1], 'answer_text': ['']}   
116064     bengali        {'answer_start': [-1], 'answer_text': ['']}   
116065    japanese        {'answer_start': [-1], 'answer_text': ['']}   
116066     english        {'answer_start': [-1], 'answer_text': ['']}   

                                       document_plaintext  \
0       Charles Hoy Fort (6. elokuuta (joidenkin lähte...   
1       “ダン”こと、ダニエル・ジャドソン・キャラハンは1890年7月26日、カリフォルニア州サンフ...   
2       వేప (లాటిన్ Azadirachta indica, syn. Melia aza...   
3       চেঙ্গিজ খান (মঙ্গোলীয়: Чингис Хаан  আ-ধ্ব-ব: ...   
4       రెయ్యలగడ్ద, విశాఖపట్నం జిల్లా, గంగరాజు మాడుగుల...   
...                                                   ...   
116062  Hingga tahun 626, situasi makin memanas, Li Sh...   
116063  وأشار هؤلاء الإخصائيون إلى أن “صداع الآيس كريم...   
116064  উপমান: যার সাথে তুলনা করা হয়।\nউপমেয়: যাকে ত...   
116065  \nベートーヴェンと同様に自然を愛好し、よくウィーン周辺の森を散策した。その際にキャンディを...   
116066  The previous mayor, Bill Laforet faced a recal...   

                                             document_url  
0            https://fi.wikipedia.org/wiki/Charles%20Fort  
1       https://ja.wikipedia.org/wiki/%E3%83%80%E3%83%...  
2       https://te.wikipedia.org/wiki/%E0%B0%B5%E0%B1%...  
3       https://bn.wikipedia.org/wiki/%E0%A6%9A%E0%A7%...  
4       https://te.wikipedia.org/wiki/%E0%B0%B0%E0%B1%...  
...                                                   ...  
116062  https://id.wikipedia.org/wiki/Kaisar%20Tang%20...  
116063  https://ar.wikipedia.org/wiki/%D9%85%D8%AB%D9%...  
116064  https://bn.wikipedia.org/wiki/%E0%A6%AC%E0%A6%...  
116065  https://ja.wikipedia.org/wiki/%E3%83%A8%E3%83%...  
116066  https://en.wikipedia.org/wiki/Mahwah%2C%20New%...  

[116067 rows x 6 columns]

In [49]:
new_df = []
new_vs = []
for i in range(len(df)):
    if df.iloc[i,2] == 'japanese' or df.iloc[i,2] == 'finnish' or df.iloc[i,2] == 'english':
        new_df.append(df.loc[i, :])
for i in range(len(vs)):
    if vs.iloc[i,2] == 'japanese' or vs.iloc[i,2] == 'finnish' or vs.iloc[i,2] == 'english':
        new_vs.append(vs.loc[i, :])
df = pd.DataFrame(new_df) #only with english, japanese or finnish text
vs = pd.DataFrame(new_vs) #only with english, japanese or finnish text

In [50]:
df

question_text  \
0                        Milloin Charles Fort syntyi?   
1                         “ダン” ダニエル・ジャドソン・キャラハンの出身はどこ   
10                                 Mitä on altruismi?   
12        Mikä oli Wilhelm Wagner viimeinen sävellys?   
13                              Missä Harz sijaitsee?   
...                                               ...   
116055  Who developed the first thermonuclear weapon?   
116059                        ギュスターヴ・シャルパンティエはいつ生まれた？   
116060                                   彭 徳懐はいつ生まれた？   
116065                                   ブラームスの出身はどこ？   
116066          What is the population of Mahwah, NJ?   

                    document_title  language  \
0                     Charles Fort   finnish   
1                     ダニエル・J・キャラハン  japanese   
10                       Altruismi   finnish   
12                  Richard Wagner   finnish   
13                            Harz   finnish   
...                            ...       ...   
116055  History of nuclear weapons   english   
116059             ギュスターヴ・シャルパンティエ  japanese   
116060                       彭徳懐故居  japanese   
116065                  ヨハネス・ブラームス  japanese   
116066          Mahwah, New Jersey   english   

                                              annotations  \
0       {'answer_start': [18], 'answer_text': ['6. elo...   
1       {'answer_start': [35], 'answer_text': ['カリフォルニ...   
10      {'answer_start': [44], 'answer_text': ['epäits...   
12      {'answer_start': [597], 'answer_text': ['Parsi...   
13      {'answer_start': [25], 'answer_text': ['Pohjoi...   
...                                                   ...   
116055        {'answer_start': [-1], 'answer_text': ['']}   
116059        {'answer_start': [-1], 'answer_text': ['']}   
116060        {'answer_start': [-1], 'answer_text': ['']}   
116065        {'answer_start': [-1], 'answer_text': ['']}   
116066        {'answer_start': [-1], 'answer_text': ['']}   

                                       document_plaintext  \
0       Charles Hoy Fort (6. elokuuta (joidenkin lähte...   
1       “ダン”こと、ダニエル・ジャドソン・キャラハンは1890年7月26日、カリフォルニア州サンフ...   
10      \n\n\nAltruismi ([1],  ”toinen”[2]) tarkoittaa...   
12      Wagnerin mestariteoksia ovat hänen myöhäiskaud...   
13      \n\nHarz on horstivuoristo Pohjois-Saksassa[1]...   
...                                                   ...   
116055  In the end, President Truman made the final de...   
116059  ただし、第一次世界大戦時に負傷兵のための音楽会を主宰し、自作の指揮も行うなど隠棲することはな...   
116060  彭徳懐故居（ほうとくかいこきょ）は、中華人民共和国の政治家で軍人（中華人民共和国元帥）だった...   
116065  \nベートーヴェンと同様に自然を愛好し、よくウィーン周辺の森を散策した。その際にキャンディを...   
116066  The previous mayor, Bill Laforet faced a recal...   

                                             document_url  
0            https://fi.wikipedia.org/wiki/Charles%20Fort  
1       https://ja.wikipedia.org/wiki/%E3%83%80%E3%83%...  
10                https://fi.wikipedia.org/wiki/Altruismi  
12         https://fi.wikipedia.org/wiki/Richard%20Wagner  
13                     https://fi.wikipedia.org/wiki/Harz  
...                                                   ...  
116055  https://en.wikipedia.org/wiki/History%20of%20n...  
116059  https://ja.wikipedia.org/wiki/%E3%82%AE%E3%83%...  
116060  https://ja.wikipedia.org/wiki/%E5%BD%AD%E5%BE%...  
116065  https://ja.wikipedia.org/wiki/%E3%83%A8%E3%83%...  
116066  https://en.wikipedia.org/wiki/Mahwah%2C%20New%...  

[29868 rows x 6 columns]

In [51]:
from janome.tokenizer import Tokenizer as tok_jap #japanese tokenizer
tok_jap = tok_jap()
from nltk.tokenize import word_tokenize #english tokenizer
#[token for token in t.tokenize(df.iloc[1,4], wakati=True)]

In [52]:
df.iloc[3,3]['answer_text']

['Parsifal']

In [53]:
from tqdm import tqdm

tokenized_answers = {} #dictionary, key = number of iteration in the dataframe, value = answer_text, or '' if it's not answerable
tokenized_questions = {} #same as before but with questions
tokenized_documents = {} #same but with documents

for i in tqdm(range(len(df))):
    if df.iloc[i,2] == 'japanese': #check the language
        tokenized_answers[i] = [token for token in tok_jap.tokenize(df.iloc[i,3]['answer_text'][0], wakati=True)]
        tokenized_questions[i] = [token for token in tok_jap.tokenize(df.iloc[i,0], wakati=True)]
        tokenized_documents[i] = [token for token in tok_jap.tokenize(df.iloc[i,4], wakati=True)]
    if df.iloc[i,2] == 'english':
        tokenized_answers[i] = word_tokenize(df.iloc[i,3]['answer_text'][0])
        tokenized_questions[i] = word_tokenize(df.iloc[i,0])
        tokenized_documents[i] = word_tokenize(df.iloc[i,4])
    if df.iloc[i,2] == 'finnish': #I used the same tokenizer, maybe we can find another one that is better for finnish
        tokenized_answers[i] = word_tokenize(df.iloc[i,3]['answer_text'][0])
        tokenized_questions[i] = word_tokenize(df.iloc[i,0])
        tokenized_documents[i] = word_tokenize(df.iloc[i,4])

100%|███████████████████████████████████████████████████████████████████████████| 29868/29868 [03:01<00:00, 164.98it/s]


In [54]:
from tqdm import tqdm

tokenized_answers_validation = {} #dictionary, key = number of iteration in the dataframe, value = answer_text, or '' if it's not answerable
tokenized_questions_validation = {} #same as before but with questions
tokenized_documents_validation = {} #same but with documents

for i in tqdm(range(len(vs))):
    if vs.iloc[i,2] == 'japanese': #check the language
        tokenized_answers_validation[i] = [token for token in tok_jap.tokenize(vs.iloc[i,3]['answer_text'][0], wakati=True)]
        tokenized_questions_validation[i] = [token for token in tok_jap.tokenize(vs.iloc[i,0], wakati=True)]
        tokenized_documents_validation[i] = [token for token in tok_jap.tokenize(vs.iloc[i,4], wakati=True)]
    if vs.iloc[i,2] == 'english':
        tokenized_answers_validation[i] = word_tokenize(vs.iloc[i,3]['answer_text'][0])
        tokenized_questions_validation[i] = word_tokenize(vs.iloc[i,0])
        tokenized_documents_validation[i] = word_tokenize(vs.iloc[i,4])
    if vs.iloc[i,2] == 'finnish': #I used the same tokenizer, maybe we can find another one that is better for finnish
        tokenized_answers_validation[i] = word_tokenize(vs.iloc[i,3]['answer_text'][0])
        tokenized_questions_validation[i] = word_tokenize(vs.iloc[i,0])
        tokenized_documents_validation[i] = word_tokenize(vs.iloc[i,4])

100%|█████████████████████████████████████████████████████████████████████████████| 3712/3712 [00:20<00:00, 177.15it/s]


# Creating trainset and validation set for the classifier

In [55]:
import nltk
#need only question and document, I don't really need the tokenization done before:
jap_training = {} 
finn_training = {}
eng_training = {}

j = 0
f = 0
e = 0


for i in range(len(df)):#create the training set already with N-grams, 1 gram is a word.
    sample_dict = {}
    sample_dict['question_tokenized'] = tokenized_questions[i]
   
    #sample_dict['question'] = df.iloc[i,0]
    #sample_dict['document'] = df.iloc[i,4]
    
    if tokenized_answers[i] == [] :
        sample_dict['label'] = 0 #not answerable question
    else:
        sample_dict['label'] = 1
        
    if df.iloc[i,2] == 'japanese':
        jap_training[j] = sample_dict
        j += 1
        continue
    elif df.iloc[i,2] == 'english':
        eng_training[e] = sample_dict
        e += 1
        continue
    elif df.iloc[i,2] == 'finnish':
        finn_training[f] = sample_dict
        f += 1
        continue


In [56]:
#validation set
import nltk

jap_val = {} 
finn_val = {}
eng_val = {}

j = 0
f = 0
e = 0


for i in range(len(vs)):
    sample_dict = {}
    sample_dict['question_tokenized'] = tokenized_questions_validation[i]
    
    if tokenized_answers_validation[i] == [] :
        sample_dict['label'] = 0 #not answerable question
    else:
        sample_dict['label'] = 1
        
    if vs.iloc[i,2] == 'japanese':
        jap_val[j] = sample_dict
        j += 1
        continue
    elif vs.iloc[i,2] == 'english':
        eng_val[e] = sample_dict
        e += 1
        continue
    elif vs.iloc[i,2] == 'finnish':
        finn_val[f] = sample_dict
        f += 1
        continue
        

## Create corpus for bag of words (one for each lang)

In [57]:
#corpus to create a vocabulary with all possible words

corpus_questions_eng = []
corpus_questions_finn = []
corpus_questions_jap = []

for x in eng_training:
    corpus_questions_eng.append(eng_training[x]['question_tokenized'])
for x in finn_training:
    corpus_questions_finn.append(finn_training[x]['question_tokenized'])
for x in jap_training:
    corpus_questions_jap.append(jap_training[x]['question_tokenized'])

In [58]:
bag_of_words_dict_eng = {}
bag_of_words_dict_finn = {}
bag_of_words_dict_jap = {}

for question in corpus_questions_eng:
    for word in question:
        if word not in bag_of_words_dict_eng:
            bag_of_words_dict_eng[word] = 1
        else:
            bag_of_words_dict_eng[word] +=1
            
for question in corpus_questions_finn:
    for word in question:
        if word not in bag_of_words_dict_finn:
            bag_of_words_dict_finn[word] = 1
        else:
            bag_of_words_dict_finn[word] +=1
            
for question in corpus_questions_jap:
    for word in question:
        if word not in bag_of_words_dict_jap:
            bag_of_words_dict_jap[word] = 1
        else:
            bag_of_words_dict_jap[word] +=1
            
#list_words = bag_of_words_dict_eng.keys()

In [59]:
len(bag_of_words_dict_jap)

5607

In [60]:
#VALIDATIO SET, the vocabulary should be the same as the training set
#I have to use the same vocabulary as the training, even for the validation set, that's why the commented part of code it's not useful
'''
bag_of_words_dict_eng = {}
for question in corpus_questions:
    for word in question:
        if word not in bag_of_words_dict_eng:
            bag_of_words_dict_eng[word] = 1
        else:
            bag_of_words_dict_eng[word] +=1
'''

'\nbag_of_words_dict_eng = {}\nfor question in corpus_questions:\n    for word in question:\n        if word not in bag_of_words_dict_eng:\n            bag_of_words_dict_eng[word] = 1\n        else:\n            bag_of_words_dict_eng[word] +=1\n'

### Top 10 words in english questions

In [61]:
sorted_words_question = dict(sorted(bag_of_words_dict_eng.items(), key=lambda item:item[1], 
reverse=True))
print(list(sorted_words_question)[:10]) #top 10 words in english questions

['?', 'the', 'When', 'was', 'What', 'is', 'of', 'How', 'in', 'did']


### Top 10 words in finnish questions

In [62]:
sorted_words_question = dict(sorted(bag_of_words_dict_finn.items(), key=lambda item:item[1], 
reverse=True))
print(list(sorted_words_question)[:10]) #top 10 words in english questions

['?', 'on', 'Milloin', 'Mikä', 'Missä', 'Kuka', 'oli', 'Mitä', 'syntyi', 'kuoli']


### Top 10 words in japanese questions

In [63]:
sorted_words_question = dict(sorted(bag_of_words_dict_jap.items(), key=lambda item:item[1], 
reverse=True))
print(list(sorted_words_question)[:10]) #top 10 words in english questions

['は', 'の', '？', 'た', 'い', 'つ', '何', 'し', 'どこ', 'が']


In [64]:
#ENGLISH
for i in eng_training:
    local_dict = {}
    for key in bag_of_words_dict_eng:
        local_dict[key] = 0
    for word in eng_training[i]['question_tokenized']:
        local_dict[word] += 1
    eng_training[i]['BOW'] = local_dict # each elemnt contains the BOW

for i in eng_val:
    local_dict = {}
    for key in bag_of_words_dict_eng:
        local_dict[key] = 0
    for word in eng_val[i]['question_tokenized']:
        if local_dict[key]:
            local_dict[word] += 1
    eng_val[i]['BOW'] = local_dict # each elemnt contains the BOW
    

In [65]:
#FINNISH
for i in finn_training:
    local_dict = {}
    #empty dict with same words
    for key in bag_of_words_dict_finn:
        local_dict[key] = 0
    for word in finn_training[i]['question_tokenized']:
        local_dict[word] += 1
    finn_training[i]['BOW'] = local_dict # each elemnt contains the BOW

for i in finn_val:
    local_dict = {}
    for key in bag_of_words_dict_finn:
        local_dict[key] = 0
    for word in finn_val[i]['question_tokenized']:
        if local_dict[key]:
            local_dict[word] += 1
    finn_val[i]['BOW'] = local_dict # each elemnt contains the BOW

In [66]:
#JAPANESE
for i in jap_training:
    local_dict = {}
    #empty dict with same words
    for key in bag_of_words_dict_jap:
        local_dict[key] = 0
    for word in jap_training[i]['question_tokenized']:
        local_dict[word] += 1
    jap_training[i]['BOW'] = local_dict # each elemnt contains the BOW

for i in jap_val:
    local_dict = {}
    for key in bag_of_words_dict_jap:
        local_dict[key] = 0
    for word in jap_val[i]['question_tokenized']:
        if local_dict[key]:
            local_dict[word] += 1
    jap_val[i]['BOW'] = local_dict # each elemnt contains the BOW


In [67]:
#np.array(list(eng_training[1]['BOW'].values())) #CONVERT BOW to ARRAY to be used in classification

## ENGLISH model

In [93]:
X = []
y = [] #0 not answ, 1 is answ.
X_VAL = []
Y_VAL = []
for i in eng_training:
    X.append(np.array(list(eng_training[i]['BOW'].values())))
    y.append(eng_training[i]['label'])
    
for i in eng_val:
    X_VAL.append(np.array(list(eng_val[i]['BOW'].values())))
    Y_VAL.append(eng_val[i]['label'])

In [69]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

LR = LogisticRegression()
LR.fit(X, y)
y_pred = LR.predict(X)
#training accuracy score
accuracy_score(y, y_pred)*100

50.02030044660982

In [70]:
#accuracy score on val_set
y_pred = LR.predict(X_VAL)
accuracy_score(Y_VAL, y_pred)*100

50.0

## FINNISH model

In [71]:
X = []
y = [] #0 not answ, 1 is answ.
X_VAL = []
Y_VAL = []
for i in finn_training:
    X.append(np.array(list(finn_training[i]['BOW'].values())))
    y.append(finn_training[i]['label'])
    
for i in finn_val:
    X_VAL.append(np.array(list(finn_val[i]['BOW'].values())))
    Y_VAL.append(finn_val[i]['label'])

In [72]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

#creating decision tree
LR = LogisticRegression()
#training decision tree
LR.fit(X, y)
y_pred = LR.predict(X)
#training accuracy score
accuracy_score(y, y_pred)*100

50.04014305525144

In [73]:
#accuracy score on val_set
y_pred = LR.predict(X_VAL)
accuracy_score(Y_VAL, y_pred)*100

50.0

# JAPANESE model

In [74]:
X = []
y = [] #0 not answ, 1 is answ.
X_VAL = []
Y_VAL = []
for i in jap_training:
    X.append(np.array(list(jap_training[i]['BOW'].values())))
    y.append(jap_training[i]['label'])
    
for i in jap_val:
    X_VAL.append(np.array(list(jap_val[i]['BOW'].values())))
    Y_VAL.append(jap_val[i]['label'])

In [75]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

#creating decision tree
LR = LogisticRegression()
#training decision tree
LR.fit(X, y)
y_pred = LR.predict(X)
#training accuracy score
accuracy_score(y, y_pred)*100

50.01139211665527

In [76]:
#accuracy score on val_set
y_pred = LR.predict(X_VAL)
accuracy_score(Y_VAL, y_pred)*100

50.0

# I tried to use countVectorizer for the english data in order to compare my method to the one already implemented, the results of the classifier are the same, this should mean that there shouldn't be major errors in my previous code, I think also that my bow is more reliable than the countvectorizer as we can see by the top english question words for the countVectorizer BOW

In [77]:
fake_corpus = [" ".join(x) for x in corpus_questions_eng]

In [78]:
fake_corpus

['When was quantum field theory developed ?',
 'Who was the first Nobel prize winner for Literature ?',
 'When is the dialectical method used ?',
 'Who invented Hangul ?',
 'What do Grasshoppers eat ?',
 'How large is the Kerman province of southeastern Iran ?',
 'When was Guitar Hero Live first released ?',
 'When were bluebonnets named the state flower of Texas ?',
 'Who created the series Clannad ?',
 'When was the USS Taylor built ?',
 "What 's the difference between man-slaughter and homicide ?",
 'When did DC comics first introduce the Guardians of the Universe ?',
 'What is the largest parrot in New Zealand ?',
 "When was the first Assassin 's Creed released ?",
 "What percentage of the Earth 's atmosphere is oxygen ?",
 'When was the X-Men cartoon television series first aired ?',
 'When was the Battle of Suoi Chau Pha fought ?',
 'How old was Cho Namchul when he died ?',
 "What is the Navy 's military mascot ?",
 'How many permanent members of the United Nations Security Counc

In [113]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
 
vectorizer = CountVectorizer()

# Fit the bag-of-words model
#
bag = vectorizer.fit_transform(fake_corpus)
#
# Get unique words / tokens found in all the documents. The unique words / tokens represents
# the features
#
print(vectorizer.get_feature_names())
#
# Associate the indices with each unique word
#
print(vectorizer.vocabulary_)
#
# Print the numerical feature vector
#
print(bag.toarray())

['1000', '101', '11', '1100', '14', '1499', '1650', '16th', '1788', '1817', '1914', '1916', '1924', '1935', '1945', '1950', '1983', '1990', '1993', '1994', '1996', '1999', '2000', '2001', '2003', '2006', '2007', '2008', '2009', '2010', '2012', '2014', '2015', '2016', '2017', '2018', '2050', '2077', '21', '24', '30', '3000', '39', '3d', '428', '44', '451', '470', '49ers', '4k', '60', '69', '76', '777', '83', '85th', '90', '90210', '919', '97', '9th', 'a6', 'aaron', 'abandonware', 'abbaye', 'abc', 'abe', 'abel', 'abi', 'abolish', 'abolished', 'aboriginal', 'abortion', 'about', 'abrolhos', 'abs', 'abundant', 'ac', 'academy', 'accepted', 'accomplishment', 'according', 'acetaminophen', 'achieved', 'achieving', 'acid', 'acquired', 'acquisition', 'across', 'act', 'acting', 'action', 'actions', 'active', 'activism', 'activity', 'actor', 'actors', 'actress', 'acts', 'actually', 'ad', 'adams', 'adaptation', 'adapted', 'address', 'adelaide', 'adiseshiah', 'administrative', 'admiral', 'admiralty',

C:\Program Files\Python310\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [114]:
fake_val_corpus = []
for i in eng_val:
    fake_val = " ".join(eng_val[i]['question_tokenized'])
    fake_val_corpus.append(fake_val)

In [115]:
bag_val = vectorizer.transform(fake_val_corpus)

In [116]:
print(bag.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [117]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

#creating decision tree
LR = LogisticRegression()
#training decision tree
LR.fit(bag.toarray(), y)
y_pred = LR.predict(bag.toarray())
#training accuracy score
accuracy_score(y, y_pred)*100

50.02030044660982

In [118]:
#accuracy score on val_set
y_pred = LR.predict(bag_val.toarray())
accuracy_score(Y_VAL, y_pred)*100

50.0

In [123]:
#MY METHOD
sorted_words_question = dict(sorted(bag_of_words_dict_eng.items(), key=lambda item:item[1], 
reverse=True))
print(list(sorted_words_question)[:10]) #top 10 words in english questions

['?', 'the', 'When', 'was', 'What', 'is', 'of', 'How', 'in', 'did']


In [124]:
#COUNT VECTORIZER
sorted_words_question = dict(sorted(vectorizer.vocabulary_.items(), key=lambda item:item[1], 
reverse=True))
print(list(sorted_words_question)[:10]) #top 10 words in english questions
# I don't think 'ḥakam' should have more counts than 'When' in a english corpus about questions

['ḥakam', 'ḍāhirī', 'ʿabd', 'śląski', 'águas', 'zürich', 'zylom', 'zuni', 'zoro', 'zopiclone']


### --------------------------------------------------------------------------------------------------------------------------------------------------------------